version: '3.4'

services:
  sqldata:
    container_name: sqldata
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - SA_PASSWORD=Pass@@word
        - ACCEPT_EULA=Y
    ports:
        - 5433:1433
    volumes:
        - sqldata:/var/opt/mssql
    deploy:
        replicas: 1
        resources:
          limits:
              memory: 1500M
              cpus: "1"

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Pass!!word
    ports:
        - 27017:27017
    volumes:
        - mongodata:/data/db
        - mongoconfig:/data/configdb
    deploy:
        replicas: 1
        resources:
          limits:
              memory: 1500M
              cpus: "1"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Pass!!word
      ME_CONFIG_MONGODB_URL: mongodb://root:Pass!!word@mongodb:27017/

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: masstransit/rabbitmq:latest
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
          cpus: "0.5"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
        
volumes:
  sqldata:
    external: false
  mongodata:
    external: false
  mongoconfig:
    external: false
  rabbitmq:
    external: false